
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

import java_cup.runtime.*;
import java.io.*;
import java.util.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b beta 20140226 generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class parser extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\114\000\002\002\004\000\002\016\004\000\002\020" +
    "\003\000\002\020\004\000\002\020\004\000\002\017\003" +
    "\000\002\017\003\000\002\017\003\000\002\017\003\000" +
    "\002\017\005\000\002\017\006\000\002\017\005\000\002" +
    "\017\003\000\002\017\004\000\002\025\004\000\002\021" +
    "\002\000\002\021\004\000\002\022\005\000\002\022\005" +
    "\000\002\006\003\000\002\006\003\000\002\023\003\000" +
    "\002\032\002\000\002\023\006\000\002\003\003\000\002" +
    "\003\004\000\002\024\006\000\002\024\006\000\002\024" +
    "\006\000\002\024\005\000\002\024\005\000\002\024\005" +
    "\000\002\026\006\000\002\026\006\000\002\026\006\000" +
    "\002\005\005\000\002\005\005\000\002\005\005\000\002" +
    "\005\005\000\002\005\005\000\002\005\005\000\002\005" +
    "\005\000\002\005\005\000\002\005\005\000\002\005\005" +
    "\000\002\005\005\000\002\005\005\000\002\005\005\000" +
    "\002\005\004\000\002\005\005\000\002\005\005\000\002" +
    "\005\004\000\002\005\003\000\002\002\003\000\002\002" +
    "\003\000\002\004\003\000\002\004\003\000\002\007\003" +
    "\000\002\007\003\000\002\014\004\000\002\014\003\000" +
    "\002\015\004\000\002\015\003\000\002\027\005\000\002" +
    "\027\005\000\002\030\006\000\002\011\002\000\002\031" +
    "\011\000\002\031\006\000\002\031\011\000\002\012\002" +
    "\000\002\013\002\000\002\010\005\000\002\010\005\000" +
    "\002\010\004\000\002\010\004" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\207\000\022\003\ufff2\006\ufff2\027\ufff2\030\ufff2\031" +
    "\ufff2\035\ufff2\044\ufff2\045\ufff2\001\002\000\004\002\211" +
    "\001\002\000\022\003\022\006\016\027\021\030\012\031" +
    "\014\035\026\044\023\045\007\001\002\000\022\002\uffff" +
    "\003\uffff\006\uffff\027\uffff\030\uffff\031\uffff\035\uffff\036" +
    "\uffff\001\002\000\006\003\uffed\006\uffed\001\002\000\024" +
    "\002\ufffc\003\ufffc\006\ufffc\027\ufffc\030\ufffc\031\ufffc\032" +
    "\ufffc\035\ufffc\036\ufffc\001\002\000\024\002\ufff5\003\ufff5" +
    "\006\ufff5\027\ufff5\030\ufff5\031\ufff5\032\ufff5\035\ufff5\036" +
    "\ufff5\001\002\000\006\003\166\033\167\001\002\000\022" +
    "\003\ufff1\006\ufff1\027\ufff1\030\ufff1\031\ufff1\035\ufff1\044" +
    "\ufff1\045\ufff1\001\002\000\006\003\166\033\167\001\002" +
    "\000\024\002\ufffb\003\ufffb\006\ufffb\027\ufffb\030\ufffb\031" +
    "\ufffb\032\ufffb\035\ufffb\036\ufffb\001\002\000\050\007\uffe9" +
    "\010\uffe9\011\uffe9\012\uffe9\013\uffe9\014\uffe9\015\uffe9\016" +
    "\uffe9\017\uffe9\020\uffe9\021\uffe9\022\uffe9\024\uffe9\025\uffe9" +
    "\034\uffe9\040\147\041\uffe9\042\uffe9\043\uffe9\001\002\000" +
    "\006\003\137\006\016\001\002\000\024\002\ufff9\003\ufff9" +
    "\006\ufff9\027\ufff9\030\ufff9\031\ufff9\032\ufff9\035\ufff9\036" +
    "\ufff9\001\002\000\006\003\132\006\016\001\002\000\022" +
    "\003\036\006\016\027\021\030\012\031\014\035\026\042" +
    "\034\043\035\001\002\000\006\003\uffee\006\uffee\001\002" +
    "\000\006\042\125\043\124\001\002\000\020\002\000\003" +
    "\036\006\016\027\021\030\012\031\014\035\026\001\002" +
    "\000\016\003\031\006\016\027\021\030\012\031\014\035" +
    "\026\001\002\000\024\002\ufffa\003\ufffa\006\ufffa\027\ufffa" +
    "\030\ufffa\031\ufffa\032\ufffa\035\ufffa\036\ufffa\001\002\000" +
    "\020\003\122\006\016\027\021\030\012\031\014\035\026" +
    "\036\120\001\002\000\024\003\036\006\016\027\021\030" +
    "\012\031\014\035\026\036\032\042\034\043\035\001\002" +
    "\000\024\002\ufff6\003\ufff6\006\ufff6\027\ufff6\030\ufff6\031" +
    "\ufff6\032\ufff6\035\ufff6\036\ufff6\001\002\000\022\002\ufffd" +
    "\003\ufffd\006\ufffd\027\ufffd\030\ufffd\031\ufffd\035\ufffd\036" +
    "\ufffd\001\002\000\024\002\ufff4\003\ufff4\006\ufff4\027\ufff4" +
    "\030\ufff4\031\ufff4\032\ufff4\035\ufff4\036\ufff4\001\002\000" +
    "\022\004\043\005\052\006\016\007\046\010\041\023\054" +
    "\026\051\033\037\001\002\000\006\042\034\043\035\001" +
    "\002\000\022\004\043\005\052\006\016\007\046\010\041" +
    "\023\054\026\051\033\037\001\002\000\042\007\uffc9\010" +
    "\uffc9\011\uffc9\012\uffc9\013\uffc9\014\uffc9\015\uffc9\016\uffc9" +
    "\017\uffc9\020\uffc9\021\uffc9\022\uffc9\024\uffc9\025\uffc9\034" +
    "\uffc9\042\uffc9\001\002\000\006\004\uffc7\005\uffc7\001\002" +
    "\000\042\007\uffcc\010\uffcc\011\uffcc\012\uffcc\013\uffcc\014" +
    "\uffcc\015\uffcc\016\uffcc\017\uffcc\020\uffcc\021\uffcc\022\uffcc" +
    "\024\uffcc\025\uffcc\034\uffcc\042\uffcc\001\002\000\042\007" +
    "\uffc5\010\uffc5\011\uffc5\012\uffc5\013\uffc5\014\uffc5\015\uffc5" +
    "\016\uffc5\017\uffc5\020\uffc5\021\uffc5\022\uffc5\024\uffc5\025" +
    "\uffc5\034\uffc5\042\uffc5\001\002\000\042\007\uffcb\010\uffcb" +
    "\011\uffcb\012\uffcb\013\uffcb\014\uffcb\015\uffcb\016\uffcb\017" +
    "\uffcb\020\uffcb\021\uffcb\022\uffcb\024\uffcb\025\uffcb\034\uffcb" +
    "\042\uffcb\001\002\000\042\007\uffca\010\uffca\011\uffca\012" +
    "\uffca\013\uffca\014\uffca\015\uffca\016\uffca\017\uffca\020\uffca" +
    "\021\uffca\022\uffca\024\uffca\025\uffca\034\uffca\042\uffca\001" +
    "\002\000\006\004\uffc8\005\uffc8\001\002\000\040\007\063" +
    "\010\056\011\062\012\065\013\071\014\070\015\060\016" +
    "\067\017\073\020\061\021\057\022\072\024\066\025\064" +
    "\042\115\001\002\000\006\004\114\005\113\001\002\000" +
    "\022\004\043\005\052\006\016\007\046\010\041\023\054" +
    "\026\051\033\037\001\002\000\042\007\uffc3\010\uffc3\011" +
    "\uffc3\012\uffc3\013\uffc3\014\uffc3\015\uffc3\016\uffc3\017\uffc3" +
    "\020\uffc3\021\uffc3\022\uffc3\024\uffc3\025\uffc3\034\uffc3\042" +
    "\uffc3\001\002\000\042\007\uffcd\010\uffcd\011\uffcd\012\uffcd" +
    "\013\uffcd\014\uffcd\015\uffcd\016\uffcd\017\uffcd\020\uffcd\021" +
    "\uffcd\022\uffcd\024\uffcd\025\uffcd\034\uffcd\042\uffcd\001\002" +
    "\000\022\004\043\005\052\006\016\007\046\010\041\023" +
    "\054\026\051\033\037\001\002\000\042\007\uffd1\010\uffd1" +
    "\011\uffd1\012\uffd1\013\uffd1\014\uffd1\015\uffd1\016\uffd1\017" +
    "\uffd1\020\uffd1\021\uffd1\022\uffd1\024\uffd1\025\uffd1\034\uffd1" +
    "\042\uffd1\001\002\000\022\004\043\005\052\006\016\007" +
    "\046\010\041\023\054\026\051\033\037\001\002\000\022" +
    "\004\043\005\052\006\016\007\046\010\041\023\054\026" +
    "\051\033\037\001\002\000\022\004\043\005\052\006\016" +
    "\007\046\010\041\023\054\026\051\033\037\001\002\000" +
    "\022\004\043\005\052\006\016\007\046\010\041\023\054" +
    "\026\051\033\037\001\002\000\022\004\043\005\052\006" +
    "\016\007\046\010\041\023\054\026\051\033\037\001\002" +
    "\000\022\004\043\005\052\006\016\007\046\010\041\023" +
    "\054\026\051\033\037\001\002\000\022\004\043\005\052" +
    "\006\016\007\046\010\041\023\054\026\051\033\037\001" +
    "\002\000\022\004\043\005\052\006\016\007\046\010\041" +
    "\023\054\026\051\033\037\001\002\000\022\004\043\005" +
    "\052\006\016\007\046\010\041\023\054\026\051\033\037" +
    "\001\002\000\022\004\043\005\052\006\016\007\046\010" +
    "\041\023\054\026\051\033\037\001\002\000\022\004\043" +
    "\005\052\006\016\007\046\010\041\023\054\026\051\033" +
    "\037\001\002\000\022\004\043\005\052\006\016\007\046" +
    "\010\041\023\054\026\051\033\037\001\002\000\022\004" +
    "\043\005\052\006\016\007\046\010\041\023\054\026\051" +
    "\033\037\001\002\000\022\004\043\005\052\006\016\007" +
    "\046\010\041\023\054\026\051\033\037\001\002\000\042" +
    "\007\063\010\056\011\062\012\065\013\071\014\070\015" +
    "\060\016\067\017\uffd9\020\uffd9\021\uffd9\022\uffd9\024\uffd9" +
    "\025\uffd9\034\uffd9\042\uffd9\001\002\000\042\007\063\010" +
    "\056\011\062\012\065\013\071\014\070\015\060\016\067" +
    "\017\073\020\061\021\057\022\uffd2\024\066\025\064\034" +
    "\uffd2\042\uffd2\001\002\000\042\007\063\010\056\011\062" +
    "\012\065\013\uffd7\014\uffd7\015\uffd7\016\uffd7\017\uffd7\020" +
    "\uffd7\021\uffd7\022\uffd7\024\uffd7\025\uffd7\034\uffd7\042\uffd7" +
    "\001\002\000\042\007\063\010\056\011\062\012\065\013" +
    "\uffd6\014\uffd6\015\uffd6\016\uffd6\017\uffd6\020\uffd6\021\uffd6" +
    "\022\uffd6\024\uffd6\025\uffd6\034\uffd6\042\uffd6\001\002\000" +
    "\042\007\063\010\056\011\062\012\065\013\uffd4\014\uffd4" +
    "\015\uffd4\016\uffd4\017\uffd4\020\uffd4\021\uffd4\022\uffd4\024" +
    "\uffd4\025\uffd4\034\uffd4\042\uffd4\001\002\000\042\007\063" +
    "\010\056\011\062\012\065\013\071\014\070\015\060\016" +
    "\067\017\073\020\061\021\uffcf\022\uffcf\024\uffcf\025\uffcf" +
    "\034\uffcf\042\uffcf\001\002\000\042\007\uffdb\010\uffdb\011" +
    "\uffdb\012\uffdb\013\uffdb\014\uffdb\015\uffdb\016\uffdb\017\uffdb" +
    "\020\uffdb\021\uffdb\022\uffdb\024\uffdb\025\uffdb\034\uffdb\042" +
    "\uffdb\001\002\000\042\007\063\010\056\011\062\012\065" +
    "\013\071\014\070\015\060\016\067\017\073\020\061\021" +
    "\uffd0\022\uffd0\024\066\025\uffd0\034\uffd0\042\uffd0\001\002" +
    "\000\042\007\uffde\010\uffde\011\062\012\065\013\uffde\014" +
    "\uffde\015\uffde\016\uffde\017\uffde\020\uffde\021\uffde\022\uffde" +
    "\024\uffde\025\uffde\034\uffde\042\uffde\001\002\000\042\007" +
    "\uffdc\010\uffdc\011\uffdc\012\uffdc\013\uffdc\014\uffdc\015\uffdc" +
    "\016\uffdc\017\uffdc\020\uffdc\021\uffdc\022\uffdc\024\uffdc\025" +
    "\uffdc\034\uffdc\042\uffdc\001\002\000\042\007\063\010\056" +
    "\011\062\012\065\013\071\014\070\015\060\016\067\017" +
    "\uffd8\020\uffd8\021\uffd8\022\uffd8\024\uffd8\025\uffd8\034\uffd8" +
    "\042\uffd8\001\002\000\042\007\063\010\056\011\062\012" +
    "\065\013\uffd5\014\uffd5\015\uffd5\016\uffd5\017\uffd5\020\uffd5" +
    "\021\uffd5\022\uffd5\024\uffd5\025\uffd5\034\uffd5\042\uffd5\001" +
    "\002\000\042\007\063\010\056\011\062\012\065\013\071" +
    "\014\070\015\060\016\067\017\073\020\061\021\uffd3\022" +
    "\uffd3\024\066\025\064\034\uffd3\042\uffd3\001\002\000\042" +
    "\007\uffdd\010\uffdd\011\062\012\065\013\uffdd\014\uffdd\015" +
    "\uffdd\016\uffdd\017\uffdd\020\uffdd\021\uffdd\022\uffdd\024\uffdd" +
    "\025\uffdd\034\uffdd\042\uffdd\001\002\000\042\007\uffce\010" +
    "\uffce\011\uffce\012\uffce\013\uffce\014\uffce\015\uffce\016\uffce" +
    "\017\uffce\020\uffce\021\uffce\022\uffce\024\uffce\025\uffce\034" +
    "\uffce\042\uffce\001\002\000\042\007\uffc4\010\uffc4\011\uffc4" +
    "\012\uffc4\013\uffc4\014\uffc4\015\uffc4\016\uffc4\017\uffc4\020" +
    "\uffc4\021\uffc4\022\uffc4\024\uffc4\025\uffc4\034\uffc4\042\uffc4" +
    "\001\002\000\042\007\uffc6\010\uffc6\011\uffc6\012\uffc6\013" +
    "\uffc6\014\uffc6\015\uffc6\016\uffc6\017\uffc6\020\uffc6\021\uffc6" +
    "\022\uffc6\024\uffc6\025\uffc6\034\uffc6\042\uffc6\001\002\000" +
    "\024\002\uffe0\003\uffe0\006\uffe0\027\uffe0\030\uffe0\031\uffe0" +
    "\032\uffe0\035\uffe0\036\uffe0\001\002\000\040\007\063\010" +
    "\056\011\062\012\065\013\071\014\070\015\060\016\067" +
    "\017\073\020\061\021\057\022\072\024\066\025\064\034" +
    "\117\001\002\000\042\007\uffda\010\uffda\011\uffda\012\uffda" +
    "\013\uffda\014\uffda\015\uffda\016\uffda\017\uffda\020\uffda\021" +
    "\uffda\022\uffda\024\uffda\025\uffda\034\uffda\042\uffda\001\002" +
    "\000\024\002\ufff8\003\ufff8\006\ufff8\027\ufff8\030\ufff8\031" +
    "\ufff8\032\ufff8\035\ufff8\036\ufff8\001\002\000\022\002\ufffe" +
    "\003\ufffe\006\ufffe\027\ufffe\030\ufffe\031\ufffe\035\ufffe\036" +
    "\ufffe\001\002\000\010\036\123\042\034\043\035\001\002" +
    "\000\024\002\ufff7\003\ufff7\006\ufff7\027\ufff7\030\ufff7\031" +
    "\ufff7\032\ufff7\035\ufff7\036\ufff7\001\002\000\024\003\127" +
    "\004\043\005\052\006\016\007\046\010\041\023\054\026" +
    "\051\033\037\001\002\000\024\002\ufff3\003\ufff3\006\ufff3" +
    "\027\ufff3\030\ufff3\031\ufff3\032\ufff3\035\ufff3\036\ufff3\001" +
    "\002\000\040\007\063\010\056\011\062\012\065\013\071" +
    "\014\070\015\060\016\067\017\073\020\061\021\057\022" +
    "\072\024\066\025\064\042\131\001\002\000\004\042\130" +
    "\001\002\000\024\002\uffdf\003\uffdf\006\uffdf\027\uffdf\030" +
    "\uffdf\031\uffdf\032\uffdf\035\uffdf\036\uffdf\001\002\000\024" +
    "\002\uffe1\003\uffe1\006\uffe1\027\uffe1\030\uffe1\031\uffe1\032" +
    "\uffe1\035\uffe1\036\uffe1\001\002\000\004\042\135\001\002" +
    "\000\004\042\134\001\002\000\024\002\uffc2\003\uffc2\006" +
    "\uffc2\027\uffc2\030\uffc2\031\uffc2\032\uffc2\035\uffc2\036\uffc2" +
    "\001\002\000\024\002\uffc1\003\uffc1\006\uffc1\027\uffc1\030" +
    "\uffc1\031\uffc1\032\uffc1\035\uffc1\036\uffc1\001\002\000\006" +
    "\041\143\042\142\001\002\000\004\042\141\001\002\000" +
    "\006\041\uffec\042\uffec\001\002\000\022\003\uffef\006\uffef" +
    "\027\uffef\030\uffef\031\uffef\035\uffef\044\uffef\045\uffef\001" +
    "\002\000\022\003\ufff0\006\ufff0\027\ufff0\030\ufff0\031\ufff0" +
    "\035\ufff0\044\ufff0\045\ufff0\001\002\000\004\006\uffeb\001" +
    "\002\000\004\006\016\001\002\000\006\041\uffea\042\uffea" +
    "\001\002\000\052\003\156\007\uffe8\010\uffe8\011\uffe8\012" +
    "\uffe8\013\uffe8\014\uffe8\015\uffe8\016\uffe8\017\uffe8\020\uffe8" +
    "\021\uffe8\022\uffe8\024\uffe8\025\uffe8\034\uffe8\040\157\041" +
    "\uffe8\042\uffe8\043\uffe8\001\002\000\010\003\151\004\152" +
    "\006\150\001\002\000\004\037\155\001\002\000\004\037" +
    "\154\001\002\000\004\037\153\001\002\000\052\003\uffe4" +
    "\007\uffe4\010\uffe4\011\uffe4\012\uffe4\013\uffe4\014\uffe4\015" +
    "\uffe4\016\uffe4\017\uffe4\020\uffe4\021\uffe4\022\uffe4\024\uffe4" +
    "\025\uffe4\034\uffe4\040\uffe4\041\uffe4\042\uffe4\043\uffe4\001" +
    "\002\000\052\003\uffe2\007\uffe2\010\uffe2\011\uffe2\012\uffe2" +
    "\013\uffe2\014\uffe2\015\uffe2\016\uffe2\017\uffe2\020\uffe2\021" +
    "\uffe2\022\uffe2\024\uffe2\025\uffe2\034\uffe2\040\uffe2\041\uffe2" +
    "\042\uffe2\043\uffe2\001\002\000\052\003\uffe3\007\uffe3\010" +
    "\uffe3\011\uffe3\012\uffe3\013\uffe3\014\uffe3\015\uffe3\016\uffe3" +
    "\017\uffe3\020\uffe3\021\uffe3\022\uffe3\024\uffe3\025\uffe3\034" +
    "\uffe3\040\uffe3\041\uffe3\042\uffe3\043\uffe3\001\002\000\004" +
    "\006\164\001\002\000\006\004\161\006\160\001\002\000" +
    "\004\037\163\001\002\000\004\037\162\001\002\000\052" +
    "\003\uffe7\007\uffe7\010\uffe7\011\uffe7\012\uffe7\013\uffe7\014" +
    "\uffe7\015\uffe7\016\uffe7\017\uffe7\020\uffe7\021\uffe7\022\uffe7" +
    "\024\uffe7\025\uffe7\034\uffe7\040\uffe7\041\uffe7\042\uffe7\043" +
    "\uffe7\001\002\000\052\003\uffe6\007\uffe6\010\uffe6\011\uffe6" +
    "\012\uffe6\013\uffe6\014\uffe6\015\uffe6\016\uffe6\017\uffe6\020" +
    "\uffe6\021\uffe6\022\uffe6\024\uffe6\025\uffe6\034\uffe6\040\uffe6" +
    "\041\uffe6\042\uffe6\043\uffe6\001\002\000\004\037\165\001" +
    "\002\000\052\003\uffe5\007\uffe5\010\uffe5\011\uffe5\012\uffe5" +
    "\013\uffe5\014\uffe5\015\uffe5\016\uffe5\017\uffe5\020\uffe5\021" +
    "\uffe5\022\uffe5\024\uffe5\025\uffe5\034\uffe5\040\uffe5\041\uffe5" +
    "\042\uffe5\043\uffe5\001\002\000\004\034\205\001\002\000" +
    "\024\003\202\004\043\005\052\006\016\007\046\010\041" +
    "\023\054\026\051\033\037\001\002\000\016\003\uffbb\006" +
    "\uffbb\027\uffbb\030\uffbb\031\uffbb\035\uffbb\001\002\000\016" +
    "\003\036\006\016\027\021\030\012\031\014\035\026\001" +
    "\002\000\024\002\uffbd\003\173\006\uffbd\027\uffbd\030\uffbd" +
    "\031\uffbd\032\174\035\uffbd\036\uffbd\001\002\000\016\003" +
    "\uffba\006\uffba\027\uffba\030\uffba\031\uffba\035\uffba\001\002" +
    "\000\016\003\uffba\006\uffba\027\uffba\030\uffba\031\uffba\035" +
    "\uffba\001\002\000\016\003\036\006\016\027\021\030\012" +
    "\031\014\035\026\001\002\000\024\002\uffbe\003\uffbe\006" +
    "\uffbe\027\uffbe\030\uffbe\031\uffbe\032\uffbe\035\uffbe\036\uffbe" +
    "\001\002\000\016\003\036\006\016\027\021\030\012\031" +
    "\014\035\026\001\002\000\024\002\uffbc\003\uffbc\006\uffbc" +
    "\027\uffbc\030\uffbc\031\uffbc\032\uffbc\035\uffbc\036\uffbc\001" +
    "\002\000\040\007\063\010\056\011\062\012\065\013\071" +
    "\014\070\015\060\016\067\017\073\020\061\021\057\022" +
    "\072\024\066\025\064\034\204\001\002\000\020\003\uffb6" +
    "\006\uffb6\027\uffb6\030\uffb6\031\uffb6\034\203\035\uffb6\001" +
    "\002\000\016\003\uffb8\006\uffb8\027\uffb8\030\uffb8\031\uffb8" +
    "\035\uffb8\001\002\000\016\003\uffb9\006\uffb9\027\uffb9\030" +
    "\uffb9\031\uffb9\035\uffb9\001\002\000\016\003\uffb7\006\uffb7" +
    "\027\uffb7\030\uffb7\031\uffb7\035\uffb7\001\002\000\016\003" +
    "\uffbf\006\uffbf\027\uffbf\030\uffbf\031\uffbf\035\uffbf\001\002" +
    "\000\016\003\036\006\016\027\021\030\012\031\014\035" +
    "\026\001\002\000\024\002\uffc0\003\uffc0\006\uffc0\027\uffc0" +
    "\030\uffc0\031\uffc0\032\uffc0\035\uffc0\036\uffc0\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\207\000\006\016\003\021\004\001\001\000\002\001" +
    "\001\000\026\003\023\006\016\017\005\020\024\022\012" +
    "\025\010\026\007\027\014\030\026\031\017\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\010\205\001\001\000\002\001\001\000" +
    "\004\010\167\001\001\000\002\001\001\000\004\024\145" +
    "\001\001\000\006\003\137\023\135\001\001\000\002\001" +
    "\001\000\004\003\132\001\001\000\020\003\023\017\032" +
    "\025\010\026\007\027\014\030\026\031\017\001\001\000" +
    "\002\001\001\000\002\001\001\000\020\003\023\017\120" +
    "\025\010\026\007\027\014\030\026\031\017\001\001\000" +
    "\022\003\023\017\005\020\027\025\010\026\007\027\014" +
    "\030\026\031\017\001\001\000\002\001\001\000\020\003" +
    "\023\017\120\025\010\026\007\027\014\030\026\031\017" +
    "\001\001\000\020\003\023\017\032\025\010\026\007\027" +
    "\014\030\026\031\017\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\020\002\052\003\041\004" +
    "\043\005\046\007\047\014\044\015\037\001\001\000\002" +
    "\001\001\000\020\002\052\003\041\004\043\005\115\007" +
    "\047\014\044\015\037\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\020\002\052\003\041\004\043\005" +
    "\111\007\047\014\044\015\037\001\001\000\002\001\001" +
    "\000\002\001\001\000\020\002\052\003\041\004\043\005" +
    "\054\007\047\014\044\015\037\001\001\000\002\001\001" +
    "\000\020\002\052\003\041\004\043\005\110\007\047\014" +
    "\044\015\037\001\001\000\020\002\052\003\041\004\043" +
    "\005\107\007\047\014\044\015\037\001\001\000\020\002" +
    "\052\003\041\004\043\005\106\007\047\014\044\015\037" +
    "\001\001\000\020\002\052\003\041\004\043\005\105\007" +
    "\047\014\044\015\037\001\001\000\020\002\052\003\041" +
    "\004\043\005\104\007\047\014\044\015\037\001\001\000" +
    "\020\002\052\003\041\004\043\005\103\007\047\014\044" +
    "\015\037\001\001\000\020\002\052\003\041\004\043\005" +
    "\102\007\047\014\044\015\037\001\001\000\020\002\052" +
    "\003\041\004\043\005\101\007\047\014\044\015\037\001" +
    "\001\000\020\002\052\003\041\004\043\005\100\007\047" +
    "\014\044\015\037\001\001\000\020\002\052\003\041\004" +
    "\043\005\077\007\047\014\044\015\037\001\001\000\020" +
    "\002\052\003\041\004\043\005\076\007\047\014\044\015" +
    "\037\001\001\000\020\002\052\003\041\004\043\005\075" +
    "\007\047\014\044\015\037\001\001\000\020\002\052\003" +
    "\041\004\043\005\074\007\047\014\044\015\037\001\001" +
    "\000\020\002\052\003\041\004\043\005\073\007\047\014" +
    "\044\015\037\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\020\002" +
    "\052\003\041\004\043\005\125\007\047\014\044\015\037" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\032\143\001\001\000" +
    "\004\003\144\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\002\052\003\041\004\043\005\200\007\047\014\044" +
    "\015\037\001\001\000\004\012\170\001\001\000\020\003" +
    "\023\017\171\025\010\026\007\027\014\030\026\031\017" +
    "\001\001\000\002\001\001\000\004\013\176\001\001\000" +
    "\004\013\174\001\001\000\020\003\023\017\175\025\010" +
    "\026\007\027\014\030\026\031\017\001\001\000\002\001" +
    "\001\000\020\003\023\017\177\025\010\026\007\027\014" +
    "\030\026\031\017\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\011\206\001\001\000\020\003" +
    "\023\017\207\025\010\026\007\027\014\030\026\031\017" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static int errors_found=0;
    // Redefinition of error functions
    /* The report_error function, in this program, is called only when
       an error, not managed by the error symbol, is found.
       Indeed, when errors are recognized by the error symbol, the function
       syntax_error (disabled in this program) is called.
       This program is an example of error function redefinition: two new
       functions are developed, pSynError and pSynWarning, used to print
       syntactical errors and warning, respectively. */
    public void report_error(String message, Object info) {
        errors_found++;
        System.err.println("SONO VIVO");
        if (info instanceof Symbol)
            if (((Symbol)info).left != -1){
                int line = (((Symbol)info).left)+1;
                int column = (((Symbol)info).right)+1;
                System.err.println(" (linea "+line+", colonna "+column+"): "+message);
            } else System.err.println(message);
        else System.err.println(message);
    }
    public void syntax_error(Symbol cur_token){}

    /* More error management can be added in the action code */
     
    public Symbol getToken() {
        return ((Symbol)stack.elementAt(tos));
    }
    
    /* Return semantic value of symbol in position (position) */
    public Object stack(int position) {
        return (((Symbol)stack.elementAt(tos+position)).value);
    }
    
    // Return the line number of actual symbol
    public int getLine() {
        if (((Symbol)stack.elementAt(tos)).left != -1){
            return ((Symbol)stack.elementAt(tos)).left+1;
        }else return -1;
    }
    
    public int labelNumber=1;
    
    public int genLabel() {
        return labelNumber++;
    }
    
    Hashtable <String, MySymbol> symbol_table= new Hashtable<String,MySymbol>();
    
    public Hashtable <String, Integer> TYPES= new Hashtable<String,Integer>() {{ put("INT", 1); put("DOUBLE", 2); }};;



/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$parser$actions {


     class MyVariable{
        public String name;
        public MySymbol symbol;
        
        MyVariable(String name, MySymbol symbol) {
            this.name = name;
            this.symbol = symbol;
        }
    } 

  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$parser$do_action_part00000000(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= Program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // Program ::= DeclarationList InstructionList 
            {
              Object RESULT =null;
		
                if(parser.errors_found > 0 ){
			        System.err.println("ERROR: "+ parser.errors_found +" errors were found in the program");
			        return null; 
                }
		        if(errors_found==0)
                    System.out.println("\tEND");
		    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Program",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // InstructionList ::= Instruction 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("InstructionList",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // InstructionList ::= InstructionList Instruction 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("InstructionList",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // InstructionList ::= error Instruction 
            {
              Object RESULT =null;
		
                        // Error in statement: generic statement error
                        parser.report_error("Error in a statement\n",parser.getToken());
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("InstructionList",14, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // Instruction ::= Assignment 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Instruction",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // Instruction ::= Print 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Instruction",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // Instruction ::= While 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Instruction",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // Instruction ::= If 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Instruction",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // Instruction ::= BO InstructionList BC 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Instruction",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // Instruction ::= BO InstructionList error BC 
            {
              Object RESULT =null;
		
                    // Missing ; before }: missing ';' symbol after a statement
                    parser.report_error("Missing ; before }\n",parser.getToken());
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Instruction",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // Instruction ::= BO error BC 
            {
              Object RESULT =null;
		
                    // Missing ; before }: missing ';' symbol after a statement
                    parser.report_error("Missing ; before }\n",parser.getToken());
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Instruction",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // Instruction ::= PointlessInstruction 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Instruction",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // Instruction ::= error S 
            {
              Object RESULT =null;
		
                    // Error in statement: generic statement error
                    parser.report_error("Error in a statement\n",parser.getToken());
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Instruction",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // PointlessInstruction ::= Variable S 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("PointlessInstruction",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // DeclarationList ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DeclarationList",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // DeclarationList ::= DeclarationList Declaration 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("DeclarationList",15, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // Declaration ::= Type VariableList S 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Declaration",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // Declaration ::= Type error S 
            {
              Object RESULT =null;
		
                        // Error in declaration: variable declaration error
 			            parser.report_error("Error in a declaration\n",parser.getToken());
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Declaration",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // Type ::= INT_TYPE 
            {
              String RESULT =null;
		 RESULT = "INT"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // Type ::= DOUBLE_TYPE 
            {
              String RESULT =null;
		 RESULT = "DOUBLE"; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Type",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // VariableList ::= Variable 
            {
              Object RESULT =null;
		int myVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int myVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable myVar = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                        Integer type=TYPES.get(parser.stack(-1));
                        myVar.symbol.type=type;
                        symbol_table.put(myVar.name,myVar.symbol);
                        if(errors_found==0){
                            System.out.print("\t"+(String) parser.stack(-1) + " ");  // DOUBLE, INT
                            System.out.print(myVar.name); // x[5], i
                            if(myVar.symbol.index!=null)
                                System.out.println("["+myVar.symbol.dim+"]");
                            else
                                System.out.println();
                        }
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VariableList",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // NT$0 ::= 
            {
              Object RESULT =null;
 RESULT = (String) parser.stack(-2); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",24, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // VariableList ::= VariableList C NT$0 Variable 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int myVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int myVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable myVar = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                        Integer type=TYPES.get(parser.stack(-1));
                        myVar.symbol.type=type;
                        symbol_table.put(myVar.name,myVar.symbol);
                        if(errors_found==0){
                            System.out.print("\t"+(String) parser.stack(-1) + " ");  // DOUBLE, INT
                            System.out.print(myVar.name); // x[5], i
                            if(myVar.symbol.index!=null)
                                System.out.println("["+myVar.symbol.dim+"]");
                            else
                                System.out.println();
                        }
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("VariableList",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // Variable ::= ID 
            {
              MyVariable RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new MyVariable(name, new MySymbol(null, 1));
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Variable",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // Variable ::= ID ArraySubscription 
            {
              MyVariable RESULT =null;
		int nameleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int nameright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String name = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int dimleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dimright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Object dim = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s=null;
                    if(dim instanceof Integer)
                        s=new MySymbol(null,(Integer) dim, dim);
                    else
                        s=new MySymbol(null,Integer.MAX_VALUE, (String) dim);
                            
                    RESULT = new MyVariable(name, s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Variable",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // ArraySubscription ::= ArraySubscription SO INT SC 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ArraySubscription",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // ArraySubscription ::= ArraySubscription SO ID SC 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("ArraySubscription",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // ArraySubscription ::= ArraySubscription error ID SC 
            {
              Object RESULT =null;
		
                            // Error in vector: error accessing a vector, e.g. missing '[' or 
                            parser.report_error("Error in vector: error accessing a vector: missing '['\n",parser.getToken());
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ArraySubscription",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // ArraySubscription ::= SO INT SC 
            {
              Object RESULT =null;
		int dimleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int dimright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer dim = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = dim; /* Integer */ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ArraySubscription",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // ArraySubscription ::= SO ID SC 
            {
              Object RESULT =null;
		int varleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int varright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String var = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		 RESULT = var; /* String */ 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ArraySubscription",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // ArraySubscription ::= SO error SC 
            {
              Object RESULT =null;
		
                            // wrong symbol or symbols sequence within the square brackets used for vector element access
                            parser.report_error("Error in vector: wrong symbol or symbols sequence within the square brackets used for vector element access\n",parser.getToken());
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("ArraySubscription",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // Assignment ::= Variable EQ Expression S 
            {
              Object RESULT =null;
		int myVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int myVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		MyVariable myVar = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		MyVariable expr = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                    MySymbol s=symbol_table.get(myVar.name);
                    if((s.type==TYPES.get("INT"))&&(expr.symbol.type==TYPES.get("DOUBLE")))
                        System.out.println("WARNING: Assignment of a double value to an int variable.");
                    else if((s.type==TYPES.get("DOUBLE"))&&(expr.symbol.type==TYPES.get("INT")))
                        System.out.println("WARNING: Assignment of an int value to a double variable.");
                    
                    if(s==null)
                        parser.report_error("ERROR: Variable <"+myVar.name+"> not declared!",parser.getToken());
                    else if(myVar.symbol.index instanceof Integer && myVar.symbol.dim>=s.dim)
                        parser.report_error("ERROR: Array index (<"+myVar.symbol.dim+">) exceed array size (<"+s.dim+">).",parser.getToken());
                    else if(errors_found==0){
                        System.out.println("\tEVAL "+ expr.name+((expr.symbol.index!=null)? ("["+expr.symbol.index+"]") : ("")));  // EVAL -2.0, EVAL pos 0 >
                        System.out.print("\tASS " + myVar.name); // ASS x[0], ASS pos
                        if(myVar.symbol.index!=null && symbol_table.get(myVar.name).dim>=0)
                            System.out.println("["+myVar.symbol.index+"]");
                        else
                            System.out.println();
                    }
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Assignment",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // Assignment ::= error EQ Expression S 
            {
              Object RESULT =null;
		
                            //Error in assignment: assignment error
 			                parser.report_error("Error in an assignment\n",parser.getToken());
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Assignment",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // Assignment ::= Variable EQ error S 
            {
              Object RESULT =null;
		
                            //Error in expression: mathematical, boolean or comparison expression error
 			                parser.report_error("Error in an expression\n",parser.getToken());
                        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Assignment",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // Expression ::= Expression PLUS Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }

                    RESULT = new MyVariable(e1.name+" "+e2.name+" "+op , s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // Expression ::= Expression MINUS Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    RESULT = new MyVariable(e1.name+" "+e2.name+" "+op , s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // Expression ::= Expression STAR Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    RESULT = new MyVariable(e1.name+" "+e2.name+" "+op , s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // Expression ::= Expression DIV Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    RESULT = new MyVariable(e1.name+" "+e2.name+" "+op , s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // Expression ::= RO Expression RC 
            {
              MyVariable RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // Expression ::= Expression EQ_EQ Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    
                    RESULT = new MyVariable(e1.name+((e1.symbol.index!=null)? ("["+e1.symbol.index+"]") : (""))+" "+e2.name+((e2.symbol.index!=null)? ("["+e2.symbol.index+"]") : (""))+" "+op , s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // Expression ::= Expression NOT_EQ Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    
                    RESULT = new MyVariable(e1.name+((e1.symbol.index!=null)? ("["+e1.symbol.index+"]") : (""))+" "+e2.name+((e2.symbol.index!=null)? ("["+e2.symbol.index+"]") : (""))+" "+op , s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // Expression ::= Expression MIN Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    
                    RESULT = new MyVariable(e1.name+((e1.symbol.index!=null)? ("["+e1.symbol.index+"]") : (""))+" "+e2.name+((e2.symbol.index!=null)? ("["+e2.symbol.index+"]") : (""))+" "+op , s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // Expression ::= Expression MAJ Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    
                    RESULT = new MyVariable(e1.name+((e1.symbol.index!=null)? ("["+e1.symbol.index+"]") : (""))+" "+e2.name+((e2.symbol.index!=null)? ("["+e2.symbol.index+"]") : (""))+" "+op , s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // Expression ::= Expression MIN_EQ Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    
                    RESULT = new MyVariable(e1.name+((e1.symbol.index!=null)? ("["+e1.symbol.index+"]") : (""))+" "+e2.name+((e2.symbol.index!=null)? ("["+e2.symbol.index+"]") : (""))+" "+op , s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // Expression ::= Expression MAJ_EQ Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    
                    RESULT = new MyVariable(e1.name+((e1.symbol.index!=null)? ("["+e1.symbol.index+"]") : (""))+" "+e2.name+((e2.symbol.index!=null)? ("["+e2.symbol.index+"]") : (""))+" "+op , s);
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // Expression ::= Expression LOGICAL_AND Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    
                    RESULT = new MyVariable(e1.name+((e1.symbol.index!=null)? ("["+e1.symbol.index+"]") : (""))+" "+e2.name+((e2.symbol.index!=null)? ("["+e2.symbol.index+"]") : (""))+" "+op , s);
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // Expression ::= Expression LOGICAL_OR Expression 
            {
              MyVariable RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		MyVariable e1 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e2 = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    MySymbol s = new MySymbol(e1.symbol.type,1);
                    if(e1.symbol.type!=e2.symbol.type){
                        System.out.println("WARNING: Operation between int and double, int number casted to double.");
                        s.type=TYPES.get("DOUBLE");
                    }
                    
                    RESULT = new MyVariable(e1.name+((e1.symbol.index!=null)? ("["+e1.symbol.index+"]") : (""))+" "+e2.name+((e2.symbol.index!=null)? ("["+e2.symbol.index+"]") : (""))+" "+op , s);
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // Expression ::= LOGICAL_NOT Expression 
            {
              MyVariable RESULT =null;
		int opleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int opright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String op = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable e = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new MyVariable(e.name+((e.symbol.index!=null)? ("["+e.symbol.index+"]") : (""))+" "+op , e.symbol);
                    
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // Expression ::= Expression BITWISE_OR Expression 
            {
              MyVariable RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // Expression ::= Expression BITWISE_AND Expression 
            {
              MyVariable RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // Expression ::= BITWISE_NOT Expression 
            {
              MyVariable RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // Expression ::= Term 
            {
              MyVariable RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable val = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = val; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Expression",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // Term ::= Variable 
            {
              MyVariable RESULT =null;
		int myVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int myVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable myVar = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                MySymbol s=symbol_table.get(myVar.name);
                if(s==null)
                    parser.report_error("ERROR: Variable <"+myVar.name+"> not declared!",parser.getToken());
                else if(myVar.symbol.index instanceof Integer && myVar.symbol.dim>=s.dim)
                    parser.report_error("ERROR:Array index (<"+myVar.symbol.dim+">) exceed array size (<"+s.dim+">).",parser.getToken());
                else{
                    myVar.symbol.type=s.type;
                }
                RESULT = myVar;
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Term",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // Term ::= Constant 
            {
              MyVariable RESULT =null;
		int valueleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valueright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		MyVariable value = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = value; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Term",0, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // Constant ::= SignedInt 
            {
              MyVariable RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer val = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new MyVariable(String.valueOf(val), new MySymbol( TYPES.get("INT"), 1));
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // Constant ::= SignedDouble 
            {
              MyVariable RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double val = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
                    RESULT = new MyVariable(String.valueOf(val), new MySymbol( TYPES.get("DOUBLE"), 1));
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Constant",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // Sign ::= PLUS 
            {
              String RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = val; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Sign",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // Sign ::= MINUS 
            {
              String RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		String val = (String)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = val; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Sign",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // SignedInt ::= Sign INT 
            {
              Integer RESULT =null;
		int signleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int signright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String sign = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer val = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Integer(sign+val); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("SignedInt",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // SignedInt ::= INT 
            {
              Integer RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Integer val = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = val; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("SignedInt",10, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // SignedDouble ::= Sign DOUBLE 
            {
              Double RESULT =null;
		int signleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int signright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		String sign = (String)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double val = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = new Double(sign+val); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("SignedDouble",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // SignedDouble ::= DOUBLE 
            {
              Double RESULT =null;
		int valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int valright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Double val = (Double)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 RESULT = val; 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("SignedDouble",11, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // Print ::= PRINT Variable S 
            {
              Object RESULT =null;
		int myVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int myVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		MyVariable myVar = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                MySymbol s=symbol_table.get(myVar.name);
                if(s==null)
                    parser.report_error("ERROR: Variable <"+myVar.name+"> not declared!",parser.getToken());
                else if(myVar.symbol.index instanceof Integer && myVar.symbol.dim>=s.dim)
                    parser.report_error("ERROR:Array index (<"+myVar.symbol.dim+">) exceed array size (<"+s.dim+">).",parser.getToken());
                else if(errors_found==0){
                    System.out.print("\tPRINT "+myVar.name);
                    if(myVar.symbol.index!=null)
                        System.out.println("["+myVar.symbol.index+"]");
                }
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Print",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // Print ::= PRINT error S 
            {
              Object RESULT =null;
		
                //Error in 'print' instruction: print instruction error
                parser.report_error("Error in a print\n",parser.getToken());
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Print",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // While ::= WHILE Condition Nt0 Instruction 
            {
              Object RESULT =null;
		int labelsleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int labelsright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer[] labels = (Integer[])((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                if(errors_found==0){
                    System.out.println( "\tGOTO L" +labels[0]); // Label to the WHILE
                    System.out.print( "L"+labels[1]+":"); // Label to the first instruction after the while block
                }
            
              CUP$parser$result = parser.getSymbolFactory().newSymbol("While",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // Nt0 ::= 
            {
              Integer[] RESULT =null;
		
            RESULT = new Integer[2];
            RESULT[0] = genLabel(); //labels[0]: Label to the WHILE
            RESULT[1] = genLabel(); //labels[1]: Label to the first instruction after the while block
            if(errors_found==0){
                System.out.print("L"+RESULT[0]+":"); // L1: 
                System.out.print("\tEVAL "+ (String)parser.stack(0));  // EVAL pos 0 >
                System.out.println(" \t\t/* while (line "+ parser.getLine() + ") */"); // /* while (line 18) */
                System.out.println("\tGOTOF L"+RESULT[1]); // GOTOF L2
            }
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Nt0",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // If ::= IF Condition Nt1 Instruction ELSE Nt2 Instruction 
            {
              Object RESULT =null;
		int labelElseleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int labelElseright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Integer labelElse = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int labelAfterleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int labelAfterright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer labelAfter = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            if(errors_found==0)
                System.out.print( "L"+labelAfter+":"); // Label to the first instruction after the if block
            /* COMPLETE*/
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("If",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // If ::= IF Condition Nt1 Instruction 
            {
              Object RESULT =null;
		int labelAfterleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int labelAfterright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer labelAfter = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            if(errors_found==0)
                System.out.print( "L"+labelAfter+":"); // Label to the first instruction after the if block
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("If",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // If ::= IF Condition Nt1 Instruction error Nt2 Instruction 
            {
              Object RESULT =null;
		int labelElseleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).left;
		int labelElseright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)).right;
		Integer labelElse = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int labelAfterleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int labelAfterright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Integer labelAfter = (Integer)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
            // Fundamental to add labels otherways conflicts!
            
            //Error 'else' expected in 'if' instruction: the keyword else is missing in a if construct
            parser.report_error("Error 'else' expected in 'if' instruction\n",parser.getToken());
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("If",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // Nt1 ::= 
            {
              Integer RESULT =null;
		
            RESULT = genLabel(); //label: Label to the first instruction after the if block: label of the Else block
            if(errors_found==0){
                System.out.print("\tEVAL "+ (String)parser.stack(0));  // EVAL x[i] x[j] >
                System.out.println(" \t\t/* if (line "+ parser.getLine() + ") */"); // /* if (line 22) */
                System.out.println("\tGOTOF L"+RESULT); // GOTOF L2
            }
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Nt1",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // Nt2 ::= 
            {
              Integer RESULT =null;
		
            RESULT = genLabel(); //label: Label to the first instruction after the else block
            if(errors_found==0){
                System.out.println( "\tGOTO L"+RESULT);
                System.out.print( "L"+parser.stack(-2)+":"); // Label to the first instruction after the if block: label of the Else block
            }
        
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Nt2",9, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // Condition ::= RO Expression RC 
            {
              String RESULT =null;
		int myVarleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int myVarright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		MyVariable myVar = (MyVariable)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
                    RESULT=myVar.name;
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Condition",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // Condition ::= RO error RC 
            {
              String RESULT =null;
		
                    //Error in expression: mathematical, boolean or comparison expression error
                    parser.report_error("Error in an if/while expression\n",parser.getToken());
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Condition",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // Condition ::= error RC 
            {
              String RESULT =null;
		 
                    //Error '(' expected in 'if' instruction : if a symbol '(' or ')' misses in a if instruction
                    parser.report_error("Error '(' expected in 'if/while' instruction\n",parser.getToken());
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Condition",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // Condition ::= RO error 
            {
              String RESULT =null;
		 
                    //Error ')' expected in 'if' instruction: if a symbol '(' or ')' misses in a if instruction
                    parser.report_error("Error ')' expected in 'if/while' instruction\n",parser.getToken());
                
              CUP$parser$result = parser.getSymbolFactory().newSymbol("Condition",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$parser$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
              return CUP$parser$do_action_part00000000(
                               CUP$parser$act_num,
                               CUP$parser$parser,
                               CUP$parser$stack,
                               CUP$parser$top);
    }
}

}
