
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BITWISE_NOT = 20;
  public static final int BITWISE_AND = 18;
  public static final int SO = 30;
  public static final int MAJ = 10;
  public static final int S = 32;
  public static final int DOUBLE = 3;
  public static final int SC = 29;
  public static final int INT = 2;
  public static final int BITWISE_OR = 19;
  public static final int MINUS = 6;
  public static final int STAR = 7;
  public static final int C = 31;
  public static final int DIV = 8;
  public static final int RO = 25;
  public static final int MIN_EQ = 11;
  public static final int PLUS = 5;
  public static final int MIN = 9;
  public static final int IF = 23;
  public static final int ID = 4;
  public static final int EOF = 0;
  public static final int LOGICAL_OR = 16;
  public static final int error = 1;
  public static final int RC = 26;
  public static final int INT_TYPE = 34;
  public static final int DOUBLE_TYPE = 35;
  public static final int BO = 27;
  public static final int EQ = 33;
  public static final int ELSE = 24;
  public static final int NOT_EQ = 14;
  public static final int BC = 28;
  public static final int WHILE = 22;
  public static final int LOGICAL_NOT = 17;
  public static final int LOGICAL_AND = 15;
  public static final int MAJ_EQ = 12;
  public static final int PRINT = 21;
  public static final int EQ_EQ = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "ID",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "MIN",
  "MAJ",
  "MIN_EQ",
  "MAJ_EQ",
  "EQ_EQ",
  "NOT_EQ",
  "LOGICAL_AND",
  "LOGICAL_OR",
  "LOGICAL_NOT",
  "BITWISE_AND",
  "BITWISE_OR",
  "BITWISE_NOT",
  "PRINT",
  "WHILE",
  "IF",
  "ELSE",
  "RO",
  "RC",
  "BO",
  "BC",
  "SC",
  "SO",
  "C",
  "S",
  "EQ",
  "INT_TYPE",
  "DOUBLE_TYPE"
  };
}

