
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUM = 7;
  public static final int SC = 4;
  public static final int CM = 6;
  public static final int S = 5;
  public static final int EOF = 0;
  public static final int TYPE = 9;
  public static final int ID = 8;
  public static final int SO = 3;
  public static final int error = 1;
  public static final int TIMES = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TIMES",
  "SO",
  "SC",
  "S",
  "CM",
  "NUM",
  "ID",
  "TYPE"
  };
}

