
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int VECTOR_VARIABLE = 17;
  public static final int CARET = 8;
  public static final int QUESTION = 15;
  public static final int PLUS = 3;
  public static final int SCALAR_VARIABLE = 16;
  public static final int STAR = 6;
  public static final int S = 14;
  public static final int SO = 11;
  public static final int EOF = 0;
  public static final int C = 12;
  public static final int DIV = 7;
  public static final int MINUS = 4;
  public static final int CONST = 2;
  public static final int error = 1;
  public static final int DOT = 5;
  public static final int EQ = 10;
  public static final int SC = 13;
  public static final int UMINUS = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONST",
  "PLUS",
  "MINUS",
  "DOT",
  "STAR",
  "DIV",
  "CARET",
  "UMINUS",
  "EQ",
  "SO",
  "C",
  "SC",
  "S",
  "QUESTION",
  "SCALAR_VARIABLE",
  "VECTOR_VARIABLE"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[17]=new String("VECTOR_VARIABLE");
		TT[8]=new String("CARET");
		TT[15]=new String("QUESTION");
		TT[3]=new String("PLUS");
		TT[16]=new String("SCALAR_VARIABLE");
		TT[6]=new String("STAR");
		TT[14]=new String("S");
		TT[11]=new String("SO");
		TT[0]=new String("EOF");
		TT[12]=new String("C");
		TT[7]=new String("DIV");
		TT[4]=new String("MINUS");
		TT[2]=new String("CONST");
		TT[1]=new String("error");
		TT[5]=new String("DOT");
		TT[10]=new String("EQ");
		TT[13]=new String("SC");
		TT[9]=new String("UMINUS");
	}
public String getTT(int i){return TT[i];}
}

