
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_TYPE = 40;
  public static final int BITWISE_NOT = 39;
  public static final int BITWISE_AND = 37;
  public static final int SO = 20;
  public static final int CHAR = 6;
  public static final int MAJ = 29;
  public static final int S = 22;
  public static final int DOUBLE = 8;
  public static final int SC = 19;
  public static final int INT = 7;
  public static final int BITWISE_OR = 38;
  public static final int REGISTER = 4;
  public static final int MINUS = 25;
  public static final int STAR = 26;
  public static final int STATIC = 5;
  public static final int C = 21;
  public static final int SIGNED_TYPE = 42;
  public static final int DIV = 27;
  public static final int RO = 15;
  public static final int MIN_EQ = 30;
  public static final int EXTERN = 3;
  public static final int VOID_TYPE = 48;
  public static final int PLUS = 24;
  public static final int MIN = 28;
  public static final int IF = 13;
  public static final int ID = 10;
  public static final int EOF = 0;
  public static final int LOGICAL_OR = 35;
  public static final int error = 1;
  public static final int RC = 16;
  public static final int INT_TYPE = 43;
  public static final int AUTO = 2;
  public static final int DOUBLE_TYPE = 47;
  public static final int BO = 17;
  public static final int EQ = 23;
  public static final int ELSE = 14;
  public static final int LONG_TYPE = 45;
  public static final int NOT_EQ = 33;
  public static final int BC = 18;
  public static final int WHILE = 12;
  public static final int LOGICAL_NOT = 36;
  public static final int LOGICAL_AND = 34;
  public static final int STRING = 9;
  public static final int FLOAT_TYPE = 46;
  public static final int UNSIGNED_TYPE = 44;
  public static final int MAJ_EQ = 31;
  public static final int SHORT_TYPE = 41;
  public static final int PRINT = 11;
  public static final int EQ_EQ = 32;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "AUTO",
  "EXTERN",
  "REGISTER",
  "STATIC",
  "CHAR",
  "INT",
  "DOUBLE",
  "STRING",
  "ID",
  "PRINT",
  "WHILE",
  "IF",
  "ELSE",
  "RO",
  "RC",
  "BO",
  "BC",
  "SC",
  "SO",
  "C",
  "S",
  "EQ",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "MIN",
  "MAJ",
  "MIN_EQ",
  "MAJ_EQ",
  "EQ_EQ",
  "NOT_EQ",
  "LOGICAL_AND",
  "LOGICAL_OR",
  "LOGICAL_NOT",
  "BITWISE_AND",
  "BITWISE_OR",
  "BITWISE_NOT",
  "CHAR_TYPE",
  "SHORT_TYPE",
  "SIGNED_TYPE",
  "INT_TYPE",
  "UNSIGNED_TYPE",
  "LONG_TYPE",
  "FLOAT_TYPE",
  "DOUBLE_TYPE",
  "VOID_TYPE"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[40]=new String("CHAR_TYPE");
		TT[39]=new String("BITWISE_NOT");
		TT[37]=new String("BITWISE_AND");
		TT[20]=new String("SO");
		TT[6]=new String("CHAR");
		TT[29]=new String("MAJ");
		TT[22]=new String("S");
		TT[8]=new String("DOUBLE");
		TT[19]=new String("SC");
		TT[7]=new String("INT");
		TT[38]=new String("BITWISE_OR");
		TT[4]=new String("REGISTER");
		TT[25]=new String("MINUS");
		TT[26]=new String("STAR");
		TT[5]=new String("STATIC");
		TT[21]=new String("C");
		TT[42]=new String("SIGNED_TYPE");
		TT[27]=new String("DIV");
		TT[15]=new String("RO");
		TT[30]=new String("MIN_EQ");
		TT[3]=new String("EXTERN");
		TT[48]=new String("VOID_TYPE");
		TT[24]=new String("PLUS");
		TT[28]=new String("MIN");
		TT[13]=new String("IF");
		TT[10]=new String("ID");
		TT[0]=new String("EOF");
		TT[35]=new String("LOGICAL_OR");
		TT[1]=new String("error");
		TT[16]=new String("RC");
		TT[43]=new String("INT_TYPE");
		TT[2]=new String("AUTO");
		TT[47]=new String("DOUBLE_TYPE");
		TT[17]=new String("BO");
		TT[23]=new String("EQ");
		TT[14]=new String("ELSE");
		TT[45]=new String("LONG_TYPE");
		TT[33]=new String("NOT_EQ");
		TT[18]=new String("BC");
		TT[12]=new String("WHILE");
		TT[36]=new String("LOGICAL_NOT");
		TT[34]=new String("LOGICAL_AND");
		TT[9]=new String("STRING");
		TT[46]=new String("FLOAT_TYPE");
		TT[44]=new String("UNSIGNED_TYPE");
		TT[31]=new String("MAJ_EQ");
		TT[41]=new String("SHORT_TYPE");
		TT[11]=new String("PRINT");
		TT[32]=new String("EQ_EQ");
	}
public String getTT(int i){return TT[i];}
}

