
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SBCLOSED = 33;
  public static final int DIVIDE = 24;
  public static final int ASSOP = 12;
  public static final int CONST = 8;
  public static final int RBOPEN = 30;
  public static final int EQUALS = 29;
  public static final int CASE = 17;
  public static final int STORAGE_SPEC = 6;
  public static final int DECR = 28;
  public static final int INCR = 27;
  public static final int FOR = 18;
  public static final int MINUS = 23;
  public static final int STRINGCONST = 9;
  public static final int SEMICOLON = 36;
  public static final int CBOPEN = 34;
  public static final int TYPE = 3;
  public static final int COMMA = 38;
  public static final int SIGN_MODIFIER = 4;
  public static final int PLUS = 22;
  public static final int IF = 13;
  public static final int ID = 2;
  public static final int RELOP = 10;
  public static final int EOF = 0;
  public static final int RETURN = 20;
  public static final int error = 1;
  public static final int MOD = 26;
  public static final int BREAK = 19;
  public static final int SBOPEN = 32;
  public static final int VOID = 7;
  public static final int SWITCH = 16;
  public static final int TIMES = 25;
  public static final int COLON = 37;
  public static final int ELSE = 14;
  public static final int CBCLOSED = 35;
  public static final int WHILE = 15;
  public static final int DEFAULT = 21;
  public static final int LOGOP = 11;
  public static final int RBCLOSED = 31;
  public static final int LENG_MODIFIER = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "TYPE",
  "SIGN_MODIFIER",
  "LENG_MODIFIER",
  "STORAGE_SPEC",
  "VOID",
  "CONST",
  "STRINGCONST",
  "RELOP",
  "LOGOP",
  "ASSOP",
  "IF",
  "ELSE",
  "WHILE",
  "SWITCH",
  "CASE",
  "FOR",
  "BREAK",
  "RETURN",
  "DEFAULT",
  "PLUS",
  "MINUS",
  "DIVIDE",
  "TIMES",
  "MOD",
  "INCR",
  "DECR",
  "EQUALS",
  "RBOPEN",
  "RBCLOSED",
  "SBOPEN",
  "SBCLOSED",
  "CBOPEN",
  "CBCLOSED",
  "SEMICOLON",
  "COLON",
  "COMMA"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[33]=new String("SBCLOSED");
		TT[24]=new String("DIVIDE");
		TT[12]=new String("ASSOP");
		TT[8]=new String("CONST");
		TT[30]=new String("RBOPEN");
		TT[29]=new String("EQUALS");
		TT[17]=new String("CASE");
		TT[6]=new String("STORAGE_SPEC");
		TT[28]=new String("DECR");
		TT[27]=new String("INCR");
		TT[18]=new String("FOR");
		TT[23]=new String("MINUS");
		TT[9]=new String("STRINGCONST");
		TT[36]=new String("SEMICOLON");
		TT[34]=new String("CBOPEN");
		TT[3]=new String("TYPE");
		TT[38]=new String("COMMA");
		TT[4]=new String("SIGN_MODIFIER");
		TT[22]=new String("PLUS");
		TT[13]=new String("IF");
		TT[2]=new String("ID");
		TT[10]=new String("RELOP");
		TT[0]=new String("EOF");
		TT[20]=new String("RETURN");
		TT[1]=new String("error");
		TT[26]=new String("MOD");
		TT[19]=new String("BREAK");
		TT[32]=new String("SBOPEN");
		TT[7]=new String("VOID");
		TT[16]=new String("SWITCH");
		TT[25]=new String("TIMES");
		TT[37]=new String("COLON");
		TT[14]=new String("ELSE");
		TT[35]=new String("CBCLOSED");
		TT[15]=new String("WHILE");
		TT[21]=new String("DEFAULT");
		TT[11]=new String("LOGOP");
		TT[31]=new String("RBCLOSED");
		TT[5]=new String("LENG_MODIFIER");
	}
public String getTT(int i){return TT[i];}
}

