
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BC = 13;
  public static final int AND = 29;
  public static final int DOUBLE_TYPE = 33;
  public static final int EQ_MAJ = 27;
  public static final int ELSE = 9;
  public static final int PLUS = 18;
  public static final int OR = 30;
  public static final int MAJ = 23;
  public static final int INT = 2;
  public static final int THEN = 8;
  public static final int CM = 15;
  public static final int WHILE = 7;
  public static final int STAR = 20;
  public static final int S = 17;
  public static final int RO = 10;
  public static final int NOT = 31;
  public static final int MIN_EQ = 24;
  public static final int IF = 6;
  public static final int ID = 4;
  public static final int RC = 11;
  public static final int SO = 16;
  public static final int EOF = 0;
  public static final int DIV = 21;
  public static final int MINUS = 19;
  public static final int MAJ_EQ = 26;
  public static final int EQ_MIN = 25;
  public static final int PRINT = 5;
  public static final int error = 1;
  public static final int INT_TYPE = 32;
  public static final int EQ = 28;
  public static final int MIN = 22;
  public static final int BO = 12;
  public static final int SC = 14;
  public static final int DOUBLE = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "INT",
  "DOUBLE",
  "ID",
  "PRINT",
  "IF",
  "WHILE",
  "THEN",
  "ELSE",
  "RO",
  "RC",
  "BO",
  "BC",
  "SC",
  "CM",
  "SO",
  "S",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "MIN",
  "MAJ",
  "MIN_EQ",
  "EQ_MIN",
  "MAJ_EQ",
  "EQ_MAJ",
  "EQ",
  "AND",
  "OR",
  "NOT",
  "INT_TYPE",
  "DOUBLE_TYPE"
  };
}

