
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ALPHA = 15;
  public static final int INT = 14;
  public static final int C = 3;
  public static final int DATE = 16;
  public static final int SECTION_SEPARATOR = 5;
  public static final int LI = 9;
  public static final int S = 4;
  public static final int EOF = 0;
  public static final int STRING = 7;
  public static final int ARROW = 2;
  public static final int BO = 12;
  public static final int AV = 11;
  public static final int ISBN = 8;
  public static final int SO = 13;
  public static final int error = 1;
  public static final int COL = 6;
  public static final int LS = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ARROW",
  "C",
  "S",
  "SECTION_SEPARATOR",
  "COL",
  "STRING",
  "ISBN",
  "LI",
  "LS",
  "AV",
  "BO",
  "SO",
  "INT",
  "ALPHA",
  "DATE"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[15]=new String("ALPHA");
		TT[14]=new String("INT");
		TT[3]=new String("C");
		TT[16]=new String("DATE");
		TT[5]=new String("SECTION_SEPARATOR");
		TT[9]=new String("LI");
		TT[4]=new String("S");
		TT[0]=new String("EOF");
		TT[7]=new String("STRING");
		TT[2]=new String("ARROW");
		TT[12]=new String("BO");
		TT[11]=new String("AV");
		TT[8]=new String("ISBN");
		TT[13]=new String("SO");
		TT[1]=new String("error");
		TT[6]=new String("COL");
		TT[10]=new String("LS");
	}
public String getTT(int i){return TT[i];}
}

